language: cpp
compiler: gcc
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7

install:
  - export CC=gcc-7
  - export CXX=g++-7
  - cd "${TRAVIS_BUILD_DIR}"

script:
  - cmake .
  - cmake --build .
